import type { NextPage } from 'next'
import Head from 'next/head'
import Hero from '../src/components/Hero'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Landing Page Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero 
        heading="Landing Page Next App" 
        message="Landing Page construída com Next.js e Tailwind"
        button='Book'
      />
    </div>
  )
}

export default Home
